%Proposition{
	id: 1,
	title: "Environmentally unsustainable food",
	true: "Opponents of \"environmentally unsustainable\" foods think they are knowledgeable, but studies show they are comparatively uninformed",
	false: "Opponents of \"environmentally unsustainable\" foods are just as well-informed as industry professionals",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 2,
	title: "Cannabis and the brain",
	true: "Cannabis use is associated with lasting damage to some of adolescents' cognitive functions",
	false: "Cannabis use is not at all associated with any damage to adolescents' cognitive functions - short or long term",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 3,
	title: "Violence in computer games and real life",
	true: "Research shows that violence in computer games has no effect on how violent gamers are",
	false: "Playing violent computer games makes gamers much more likely to be violent than before",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 4,
	title: "Police violence against whites and blacks",
	true: "In a simulated environment, police officers were found slightly less likely to shoot black suspects than white suspects",
	false: "In an experimental study, police officers were found 12 times more likely to shoot black suspects than white suspects.",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 5,
	title: "Race-targeted police shootings",
	true: "A recent study finds little evidence that police shootings disproportionately target black people",
	false: "A recent study finds systematic evidence that police shootings disproportionately target black people",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 6,
	title: "Depression in women who work",
	true: "Stay-at-home-moms report fewer symptoms of depression than working women",
	false: "Wives who work are much happier than stay-at-home-moms",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 7,
	title: "Race and prison sentences",
	true: "On average, black and white offenders who commit similar crimes recieve similar sentences",
	false: "Black offenders receive harsher sentences than white offenders do for the same crimes",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 8,
	title: "Prison in Australia",
	true: "In Australia, indigenous and non-indigenous offenders face similar chances of imprisonment for similar offenses",
	false: "In Australia, indigenous offenders face much higher chances of capital punishment than non-indigenous offenders for similar offenses",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 9,
	title: "Immigration and jobs",
	true: "Large influxes of migrants are linked with fewer jobs available to those born in the host country",
	false: "Large influxes of migrants strongly increase the number of jobs available to native applicants of the host country",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 10,
	title: "Race and college performance",
	true: "Blacks and Hispanics admitted to elite US colleges perform more poorly than Asians",
	false: "Blacks and Hispanics admitted to elite US colleges hugely outperform whites and Asians",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 11,
	title: "Gun control and overall violence",
	true: "In a majority of cases, historical gun control measures have had little effect on overall gun-related violence",
	false: "Historical gun control measures have consistently and drastically reduced overall gun-related violence in North America and Western Europe.",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 12,
	title: "Gender and business success",
	true: "Businesses owned by women fare worse than comparable businesses owned by men",
	false: "Businesses owned by women are much more successful than comparable businesses owned by men",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 13,
	title: "Gay parents' relationships with their kids",
	true: "Homosexual parents report slightly better relationships with their children than heterosexual parents",
	false: "A vast majority of homosexual parents report worse relationships with their children than heterosexual parents",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 14,
	title: "Multiculturalism and language",
	true: "In countries run by left-wing political parties, immigrants are more likely to be worse at speaking the official language of the new country",
	false: "In countries run by left-wing political parties, immigrants are much faster to integrate and learn the spoken language of the host country",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 15,
	title: "Monogamous relationships among gay men",
	true: "Men in same‐sex relationships are less likely to indicate that their relationship is sexually exclusive",
	false: "Men in same‐sex relationships are much more likely to be in relationships that are serious, monogamous, and sexually exclusive",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 16,
	title: "Marital status and child health",
	true: "Unmarried parents report poorer child health than married parents do",
	false: "Throughout the country, unmarried parents report much better child health than married parents do",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 17,
	title: "Quality time between mothers and children",
	true: "The more time adolescent children spend with their mothers, the less likely they are to be delinquent",
	false: "When adolescent children spend lots of time with their mothers, they are more likely to be delinquent",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 18,
	title: "Returns to green investments",
	true: "The majority of European firms have no returns on their green investments",
	false: "The majority of European firms have huge returns on their green investments",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 19,
	title: "Affirmative action and field of study",
	true: "Affirmative action students from public universities tend to graduate in less prestigious fields of study than regular students",
	false: "Affirmative action students from public universities graduate with better grades and in more prestigious fields of study than regular students",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 20,
	title: "Car crashes and driver gender",
	true: "In fatal car crashes due to distracted driving, the driver is more likely to be male than female",
	false: "In fatal car crashes due to distracted driving, the driver is more likely to be female than male",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 21,
	title: "Separation in married and unmarried families",
	true: "Children whose parents live together but are unmarried are more likely to experience their parents' separation than children whose parents are married",
	false: "Children whose parents live together but are unmarried are less likely to experience their parents' separation than children whose parents are married",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 22,
	title: "Gender and negative media coverage",
	true: "Media coverage of men is less positive than media coverage of women",
	false: "Media coverage of women is considerably more negative than media coverage of men",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 23,
	title: "Coverage of women in the media",
	true: "Conservative media dedicate slightly more coverage to women than liberal media",
	false: "Conservative media dedicate 90% less coverage to women than liberal media",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 24,
	title: "Effects of climate change policy on world hunger",
	true: "Some researchers claim that severe policies meant to fight climate change will increase global hunger more drastically than climate change itself",
	false: "There is a scientific consensus that even severe policies to fight climate change would have no negative consequences on world hunger",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 25,
	title: "Paying to fight climate change",
	true: "Most US citizens who claim to be alarmed by climate change rarely donate money to organizations working to reduce climate change",
	false: "A vast majority of US citizens alarmed by climate change donate frequently and significantly to organizations working to reduce climate change",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 26,
	title: "Marriage and happiness",
	true: "Unmarried couples who live together are not as happy as married people",
	false: "Unmarried couples who live together are much more happy than married people",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 27,
	title: "Marriage and longevity",
	true: "Among white people in the US, married women and men liver longer than unmarried couples who live together",
	false: "Among white people in the US, unmarried couples who live together live significantly longer than their married counterparts",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 28,
	title: "Impact of marriage on children's health",
	true: "Children born to married parents have slightly better health at age 5 than children born to cohabiting parents",
	false: "Children born to cohabiting parents have measurably better health at age 5 than children born to married parents",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 29,
	title: "Marriage and infidelity",
	true: "Sexual infidelity is more common among unmarried couples who live together than among married couples",
	false: "Sexual infedelity is more common among married couples than among unmarried couples who live together",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 30,
	title: "Gender and academic ability",
	true: "On average, boys are slightly better in math, while girls outperform in language",
	false: "Language and math abilities are completely indistinguishable among male and female schoolchildren",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 31,
	title: "Crime and IQ",
	true: "Crime is higher in states that have a lower average IQ",
	false: "Crime is much higher in states that have a higher average IQ",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 32,
	title: "University prestige by nation",
	true: "The United States is home to the best ranked universities in the world",
	false: "Europe leads the ranking for the best ranked universities in the world",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 33,
	title: "International cancer care",
	true: "Due to leading professionals and technological advantages, cancer patients in the United States have better survival chances than in most European countries",
	false: "Despite availability of advanced medical care, cancer patients in the US have lower survival chances than patients in both eastern and western Europe",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 34,
	title: "Legalization of marijuana",
	true: "Following legalization of marijuana use in Colorado, an increase in consumption lead to a marked increase of the number of poison center calls mentioning marijuana",
	false: "Following legalization of marijuana use in Colorado, the number of poison center calls mentioning marijuana remained extremely low despite a rise in consumption",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 35,
	title: "Illegal border crossings in Israel",
	true: "Following Israel's construction of a southern border wall between 2010 and 2013, annual numbers of illegal crossings declined",
	false: "Following Israel's construction of a southern border wall between 2010 and 2013, annual numbers of illegal crossings increased",
	post_is_false: true,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 36,
	title: "Olympic medal winners by country",
	true: "The United States have won more medals at the Summer Olympics than any other nation",
	false: "Iran has won more medals at the Summer Olympics than any other nation",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 37,
	title: "Wildfires and human-induced CO2 emissions",
	true: "Human-induced CO2 levels in the air have resulted in increased chances of wildfires in California",
	false: "Human-induced CO2 levels in the air have no impact on the likelihood of wildfires or any other natural disaster",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 38,
	title: "Abortion and mental health",
	true: "Women who have an early-stage abortion experience similar mental health to women who keep their babies",
	false: "Women who have an early-stage abortion experience much worse mental health than women who keep their babies",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 39,
	title: "Religion and the economy",
	true: "During periods when fewer people are attending church, it is more likely that the economy will experience growth",
	false: "When more people attend church, the economy grows",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 40,
	title: "Air pollution versus smoking",
	true: "Air pollution kills slightly more people than smoking does",
	false: "In the US, smoking kills 10 times as many people as air pollution",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 41,
	title: "Racist cars?",
	true: "Self-driving cars are better at detecting white pedestrians than black ones",
	false: "Self-driving cars are much better at detecting black pedestrians than white ones",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 42,
	title: "Microdosing and creativity",
	true: "\"Microdosing\" (ingesting a small amounts of LSD or similar drug) has been linked with increased creativity",
	false: "\"Microdosing\" (ingesting a little bit of LSD or similar drug) significantly damages long-term creative abilities",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 43,
	title: "Socialism and economic security",
	true: "Eastern Europeans felt economically more secure under socialism than under capitalism",
	false: "Eastern Europeans feel economically more secure and experienced less financial anxiety under capitalism than under socialism",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 44,
	title: "Foreigners and the German budget",
	true: "Foreigners do not negatively impact the German federal budget",
	false: "Foreigners burden the German federal budget, causing a negative balance",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 45,
	title: "Race and the death penalty",
	true: "White people are more likely to favor the death penalty than black people",
	false: "Many more black people favor the death penalty than white people",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 46,
	title: "Immigration and the economy",
	true: "Second-generation immigrants are among the strongest fiscal and economic contributors in the U.S.",
	false: "Second-generation immigrants are the weakest fiscal and economic contributors in the U.S.",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 47,
	title: "Race and hiring chances",
	true: "Even under identical qualifications, white people have higher chances receiving job offers than black people",
	false: "Under identical qualifications, black people have higher chances of receiving a job offer than white people",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 48,
	title: "Gender and enterpreneurship",
	true: "Investors prefer pitches by male entrepreneurs over the same pitches by female entrepreneurs",
	false: "Investors prefer pitches by female entrepreneurs over the same pitches by male entrepreneurs",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 49,
	title: "Gun control and suicide",
	true: "Stricter gun control laws in US states have resulted in lower overall suicide rates",
	false: "Stricter gun control laws in US states have had no effect on overall suicide rates",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 50,
	title: "Gender and leadership styles",
	true: "Women, more than men, manifest leadership styles associated with effective performance as leaders",
	false: "Men are much more likely than women to manifest leadership styles associated with effective performance as leaders",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 51,
	title: "Gay parents and child development",
	true: "The cognitive development of children raised by homosexual parents does not have any notable differences in comparison with children raised by heterosexual parents",
	false: "Children raised by homosexual parents experience more mental health issues than children raised by heterosexual parents",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 52,
	title: "Wage and intelligence",
	true: "On average, rich people are more likely to perform well on intelligence tests than poor people",
	false: "The poor are on average smarter than the rich",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 53,
	title: "The American Dream",
	true: "The chance that someone who is born poor becomes rich is lower in the United States than in Western Europe",
	false: "The chance that someone who is born poor becomes rich is much higher in the United States than in the rest of the world",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 54,
	title: "Muslims in Western countries",
	true: "The greater the share of immigrants in a Western country, the more accepting native citizens are of new immigration",
	false: "The greater the share of Muslims in a Western country, the more that natives want to abolish Muslim immigration completely",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 55,
	title: "Immigrant diversity and white-collar wages",
	true: "The greater the immigrant diversity in a city, the higher the wages for white-collar jobs",
	false: "Wages for white-collar jobs decrease strongly when there are more immigrants in a city, while blue-collar jobs wages remain constant",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 56,
	title: "CO2 emission effects",
	true: "Scientists have observed Arctic sea-ice loss directly following human CO2 emissions",
	false: "Scientists have observed that Arctic sea-ice loss has no association with human CO2 emissions",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 57,
	title: "Police and respect toward different races",
	true: "Police officers speak significantly less respectfully to black community members than to white ones in everyday traffic stops",
	false: "Police officers speak with equal respect to all community members, regardless of race, in stop-and-frisk encounters.",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 58,
	title: "Affirmative action and applicant quality",
	true: "Affirmative action has little effect on the quality of the best applicants for a job",
	false: "Affirmative action reduces the quality of the best applicants for a job considerably",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 59,
	title: "Global warming and mental health",
	true: "Global warming is linked with negative effects on mental health",
	false: "Increased reporting on global warming has not had any significant negative  impacts on mental health",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 60,
	title: "CEO gender and performance",
	true: "Micro-finance institutions with a female CEO and female board chairman perform slightly better than their male-led counterparts",
	false: "Micro-finance institutions led by men vastly outperform their female-led counterparts",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 61,
	title: "Responses to low masculinity test scores",
	true: "When mens' masculinity is called into question, they are more likely to respond with a homophobic attitude",
	false: "After men were told they scored low on a masculinity test, they were less likely to support war,  have homophobic attitudes, or be interested in purchasing an SUV",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 62,
	title: "Race and missing children",
	true: "Black missing children are less likely to be recovered than white missing children",
	false: "White missing children are recovered half as often as black missing children",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 63,
	title: "Female students and team productivity",
	true: "The presence of women in student teams increases overall team productivity",
	false: "Student teams with only males are much more productive than teams that also have females in them",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 64,
	title: "Melting ice?",
	true: "Annually, a significant amount of ice is lost from glacier",
	false: "The amount of ice lost from glaciers annually is negligible",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 65,
	title: "Marriage and depression",
	true: "Single people are more likely to suffer from depression than married people",
	false: "Married people are much more likely to suffer from depression than single people",
	post_is_false: false,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 66,
	title: "Latino immigrants and homicide",
	true: "When Latino immigrants move into an area, there is no increase in homicide rates",
	false: "When Latino immigrants move into an area, homicide rates increase sharply",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 67,
	title: "Longevity in the US and Germany",
	true: "Germany's relative income equality has resulted in longer life expectancies for Germans as compared to Americans",
	false: "The relative income equality in Germany means that Germans don't live as long as Americans",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 68,
	title: "Medical spending in the US and Europe",
	true: "Europeans have more doctors and hospital beds even though they spend less money on health care than Americans",
	false: "Europeans have fewer hospital beds per capita in comparison to Americans even though they spend more on health care",
	post_is_false: false,
	post_intended_as_liberal: true,
},
%Proposition{
	id: 69,
	title: "Math by country",
	true: "American students, on average, are worse at math than German students",
	false: "American students are much better at math than German students",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 70,
	title: "Tax cuts and economic performance",
	true: "US states that enacted major income tax cuts performed economically similarly to states without tax cuts",
	false: "US states that enacted major income tax cuts performed much better than states without tax cuts",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 71,
	title: "Death penality and homicide",
	true: "US states without the death penalty have similar homicide rates compared to states with the death penalty",
	false: "US states with the death penalty have had much lower homicide rates throughout history as compared to US states without the death penalty",
	post_is_false: true,
	post_intended_as_liberal: false,
},
%Proposition{
	id: 72,
	title: "Undocumented immigrants crossing the US-Mexico border",
	true: "The number of undocumented migrants attempting to cross the US - Mexico border has steadily declined over the past two decades",
	false: "The number of undocumented migrants attempting to cross the US - Mexico border has tremendously increased over the past two decades",
	post_is_false: false,
	post_intended_as_liberal: true,
},
